site_name: Hsftp - a SFTP client tool for file transfer operations
site_url: https://mdusi.github.io/hsftp/
site_description: Hsftp is a SFTP client tools for secure file transfer operations.
copyright: Copyright &copy; 2024 Maurizio Dusi

repo_url: https://github.com/mdusi/hsftp/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mauriziodusi/
    - icon: fontawesome/brands/github
      link: https://github.com/mdusi/hsftp/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/cricio/hsftp/
  
nav:
  - Getting Started: index.md
  - Examples: example.md
  - Changelog: changelog.md

theme:
  name: material
  icon: 
    logo: material/handshake
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top  
    - content.code.copy

  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
