name:                hsftp
version:             1.4.0
github:              "mdusi/hsftp"
license:             BSD-3-Clause
author:              "Maurizio Dusi"
maintainer:          "Maurizio Dusi"
copyright:           "(c) 2024 Maurizio Dusi"

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

synopsis:            A SFTP client tool for secure file transfer operations
homepage:            https://mdusi.github.io/hsftp/
category:            Utils, Network

description:         Hsftp is a command-line tool for secure file transfer operations

pkg-config-dependencies:
- libssh2

dependencies:
- base >= 4.7 && < 5
- bytestring
- libssh2
- cmdargs
- yaml
- aeson
- mtl
- time
- directory
- filepath

default-extensions:
- RecordWildCards

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hsftp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsftp

tests:
  hsftp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsftp
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - tasty-quickcheck
    - temporary
