name: Build

on: 
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - 'Dockerfile'
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
      
    services:
      sftp1:
        image: atmoz/sftp
        ports:
          - 9988:22
        env:
          SFTP_USERS: "demo:demo:::download,upload/byext,upload/anyext,upload/archive"
        volumes:
          - ./download:/home/demo/download
        options: --name sftp1

    steps:
    - uses: actions/checkout@v4
      with:
        path: repo

    - name: check test files
      id: download-volume
      run: |
        sudo mkdir -p ./download
        sudo cp ./repo/test/files/download/* ./download/
        
    - name: restart sftp container
      uses: docker://docker
      with:
        args: docker restart sftp1

    - name: post-restart check test files
      working-directory: download
      run: bash -c "[ $(find . -maxdepth 1 -type f | wc -l) -gt 0 ]"
      
    - name: install libssh2
      run: |
        sudo apt update 
        sudo apt -y install libssh2-1-dev

    - name: use cache
      id: cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-stack-${{ hashFiles('repo/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-${{ hashFiles('repo/stack.yaml') }}
          ${{ runner.os }}-stack-
        path: |
          repo/.stack-work
          ~/.stack
          !~/.stack/indices/

    - name: setup Haskell stack
      uses: haskell-actions/setup@v2
      id: setup-haskell-stack
      with:
        ghc-version: '9.8'
        enable-stack: true
        stack-version: 'latest'
        
    - name: Build and Test
      working-directory: repo
      run: stack build --system-ghc --test
