name: Build

on: [workflow_dispatch, workflow_call, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sftp1:
        image: atmoz/sftp
        ports:
          - 9988:22
        env:
          SFTP_USERS: "demo:demo:::upload"

    steps:
    - uses: actions/checkout@v4

    - name: install libssh2
      run: sudo apt update && sudo apt -y install libssh2-1-dev

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.5'
        enable-stack: true
        stack-version: 'latest'

    - name: Build and Test
      run: stack build --test
